services:
  postgres:
    build: sources/postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
  transactions:
    build:
      context: sources/transactions
      dockerfile: Dockerfile
    container_name: transactions

volumes:
  pgdata:
